default_platform(:ios)

platform :ios do
  desc "Build"
  lane :build do
    gym(
      scheme: "BoringTwitterClone",
      skip_package_ipa: true,
      skip_archive: true,
      silent: true,
      clean: true
    )
  end
end
